spring.application.name=Ecommerce-Platform
spring.data.mongodb.uri=mongodb+srv://reddyharish530_db_user:RyCJ1KDup9kdkYDl@cluster0.883nklz.mongodb.net/ecommerceDb?retryWrites=true&w=majority

spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceDB
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect