spring.application.name=Ecommerce-Platform

#spring.datasource.url=jdbc:sqlserver://ecommerce-platform.database.windows.net:1433;database=ecommerce-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=harish23@ecommerce-platform
#spring.datasource.password=Harish@#1023
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb+srv://reddyharish530_db_user:RyCJ1KDup9kdkYDl@cluster0.883nklz.mongodb.net/ecommerceDB?retryWrites=true&w=majority

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceDB
#spring.data.mongodb.database=ecommerceDB
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

#spring.datasource.hikari.initialization-fail-timeout=60000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=5
spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceDB
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update

#
#spring.datasource.hikari.initialization-fail-timeout=60000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=5
#
#

#spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce_mongo
#spring.jpa.show-sql=true
