version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EcommerceDB
    ports:
      - "3307:3306"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8082:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge